coverage:
    precision: 2
    round: down
    range: "75...100"
    status:
        project:
            default:
                target: 90%
                threshold: 1%
        patch: off
        changes: off

ignore:
    - "app/src/Validator/Constraints"

