version: "3.7"
services:

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        restart: unless-stopped
        user: ${LOCAL_USER}
        environment:
            PHP_IDE_CONFIG: serverName=${DEBUG_SERVER}
        volumes:
            - "./app/:/usr/src/app"
            - "./docker/app/php.ini:/usr/local/etc/php/php.ini:ro"
            - "./docker/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro"
        depends_on:
            - "db"

    web:
        image: nginx:1.17.6-alpine
        restart: unless-stopped
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - "./app/public/:/usr/src/app"
            - "./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro"
        depends_on:
            - "app"

    db:
        image: mariadb:10.4.11
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - "./docker/db/my.cnf:/etc/mysql/my.cnf:ro"
            - "dbdata:/var/lib/mysql"

    adminer:
        image: adminer:4.7.5
        restart: unless-stopped
        ports:
            - "${ADMINER_PORT}:8080"
        depends_on:
            - "db"

    mail:
        image: jeanberu/mailcatcher:0.7.1
        restart: unless-stopped
        ports:
            - "${MAILCATCHER_PORT}:1080"
        depends_on:
            - "app"

volumes:
    dbdata:
