name: THlEd BUGTRACKER CI

on: [push]

jobs:
  run:

    name: Run
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: ./
      with:
        php-version: 7.4

    - name: php --version
      run: |
        php -i
        php -m

    - name: Validate composer.json and composer.lock
      working-directory: ./app
      run: composer validate

    - name: Install dependencies
      working-directory: ./app
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run CI
      working-directory: ./app
      run: composer run-script ci
