name: ci-pipeline

on: [push]

jobs:
  run:

    name: Run
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.4'

    - name: Get Composer cache directory
      id: composer-cache
      working-directory: ./app
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      working-directory: ./app
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.7

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Yarn dependencies
      working-directory: ./app
      run: yarn run ci

    - name: Run CI
      working-directory: ./app
      run: composer run-script ci

    - name: Generate coverage report
      working-directory: ./app
      run: composer run-script tests-coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./app/coverage.xml
